name: mango-utilities
version: '1.0-SNAPSHOT'
main: me.sentryozvn.mangoUtilities.MangoUtilities
api-version: '1.21'
softdepend:
  - MythicMobs
  - MMOItems
  - PlaceholderAPI
depend: [CommandAPI]
permissions:
  mango.utilities.use:
    description: Allows use of Mango Utilities commands
    default: op
